name: CI Pull Requests on main

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform_check_validate_and_plan:
    uses: ./.github/workflows/reusable_terraform_check_and_plan.yml
    secrets: inherit
