name: Run Terraform Plan Against an Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests agains'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

env:
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        run: terraform init -upgrade
        continue-on-error: false

      # Validates terraform configuration
      - name: Terraform Validate
        id: validate
        if: steps.init.outcome != 'failure'
        run: terraform validate -no-color
        continue-on-error: false

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_AWS_CERTIFICATE_ARN: ${{ vars.AWS_CERTIFICATE_ARN }}
          TF_VAR_AWS_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_DOMAIN_API: ${{ vars.DOMAIN_API }}
          TF_VAR_CORS_ALLOWED_ORIGIN: ${{ vars.CORS_ALLOWED_ORIGIN }}
          TF_VAR_ENV: ${{ vars.ENV }}
          TF_VAR_USER_DATA_DELETION_CRON: ${{ vars.USER_DATA_DELETION_CRON }}
        run: terraform plan -no-color -input=false
        continue-on-error: false
